databases:
  - name: my_database
    ipAllowList: []

services:
  - type: web
    region: ohio
    name: attestation_app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
